# SOPS configuration
# https://github.com/Mic92/sops-nix
#
# Setup:
# 1. Generate age key: age-keygen -o ~/.config/sops/age/keys.txt
# 2. Add your public key below
# 3. Create secrets: sops secrets/secrets.yaml
# 4. Encrypt: sops encrypts automatically when saving

keys:
  # User age keys (from ~/.config/sops/age/keys.txt)
  - &draxel age1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

  # Host keys (generate after install with: sudo cat /etc/ssh/ssh_host_ed25519_key | ssh-to-age)
  - &toaster age1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

creation_rules:
  # Secrets accessible by draxel user
  - path_regex: secrets/user\.yaml$
    key_groups:
      - age:
          - *draxel

  # Secrets accessible by host (system services)
  - path_regex: secrets/.*\.yaml$
    key_groups:
      - age:
          - *draxel
          - *toaster
